### ISSUE TITLE
flycheck-joker currently ignores .joker file

### ISSUE THREAD

**Issue by malchmih** [candid82/flycheck-joker#2]
I'm using the latest version of joker:
```
➜ joker -v
v0.8.5
```
.joker file in the project's root (doesn't work with the file in the home directory either):
```clojure
{:known-macros [outpace.remote.service/defservice]
 :rules {:if-without-else true}}
```
From the shell linter works perfectly:
```
➜ joker --lint src/common/clj/transportal/service/dadata.clj
src/common/clj/transportal/service/dadata.clj:14:1: Parse warning: missing else branch
src/common/clj/transportal/service/dadata.clj:18:19: Parse error: Unable to resolve symbol: body
...
```
But it ignores the config completely inside the Emacs:
![image](https://user-images.githubusercontent.com/450680/31127969-fdbeba94-a858-11e7-962a-8dd0ca8aa8c1.png)

**Comment by malchmih** [comment]
I'm on the Ubuntu btw
```
➜ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
```

**Comment by candid82** [comment]
Should be fixed by https://github.com/candid82/flycheck-joker/commit/c34c3922a2e8bc918f250602e0ddf655cdcad456. The new version should appear on MELPA soon. Please let me know if the problem persists after update. 

`.joker` file in home directory *should* work with the current version though. The only way it may fail is if `HOME` env variable is not available when running `joker` from emacs.

**Comment by malchmih** [comment]
Thank you, it works as expected now! You were right, `.joker` in the home directory worked just fine, got something mixed up. 
Thank you for this great tool, it really helps our CIDER/Spacemacs Clojure workflow!
